---
# example config run by evaluate.py

# path to store evaluation results
# (pick another location when testing)
_RESULTS_PATH: "./example_experiment/evaluation_results/val/"
_MODEL_CHECKPOINT: "./example_experiment/training_run/checkpoints/best_val_checkpoint.pth"
_NEW_CKP_FORMAT: true

_MODEL_CONFIG:
  "smp_name": "Unet"
  "smp_params":
    encoder_name: "efficientnet-b4"
    encoder_weights: "imagenet"
    decoder_use_batchnorm: False
    activation: null
    classes: 1
  _CLASS_INFO:
    _MODULE_NAME: "new_models.models"
    _CLASS_NAME: "BaselineModelGetter"

# use splitter key to specify which dataset
_VAL_DATALOADER_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.dataloader"
    _CLASS_NAME: "BaselineDataloaderGetter"
  "batchsize": 8
  "shuffle": False
  "dataset":
    _CLASS_INFO:
      _MODULE_NAME: "new_datasets.datasets"
      _CLASS_NAME: "NewBaselineDatasetGetter"
    "splitter":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.splits"
        _CLASS_NAME: "GenSplit"
      "train": 0.7
      "val": 0.15
      "test": 0.15
      "seed": 1
    "label2mask":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "SingleChannelMaskNumpy"
    "augmentation":
      _CLASS_INFO:
        _MODULE_NAME: "albumentations"
        _CLASS_NAME: "Compose"
      transforms:
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "Resize"
          "height": 512
          "width": 512
          "interpolation": 2 # cubic
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "CenterCrop"
          "height": 384
          "width": 384
    "smp_preprocessing":
      "encoder_name": "efficientnet-b4"
      "pretrained": "imagenet"
      _CLASS_INFO:
        _MODULE_NAME: "segmentation_models_pytorch.encoders"
        _CLASS_NAME: "get_preprocessing_fn"
    "splitter_key": "val"
    "filters": null

_LOSSES_METRICS_CONFIG:
  "criterions_dict":
    "loss_baseline":
      "dice_smooth": 1.0E-8
      "bce_weight": 0.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "BaselineLoss"
    "loss_dice":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "SoftDice"
      "epsilon": 1.0E-8
      "pred_process":
        _CLASS_INFO:
          _MODULE_NAME: "torch.nn"
          _CLASS_NAME: "Sigmoid"
    "loss_bce":
      _CLASS_INFO:
        _MODULE_NAME: "torch.nn"
        _CLASS_NAME: "BCEWithLogitsLoss"
    "dice_metric":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "DiceMetric"
      "epsilon": 1.0E-8
      "binarize_func":
        _CLASS_INFO:
          _MODULE_NAME: "loss_utils.losses"
          _CLASS_NAME: "SigmoidBinarize"
        "thresholds": [0.5]
    "hard_dice":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "HardDice"
      "epsilon": 1.0E-8
      "binary_forward":
        _CLASS_INFO:
          _MODULE_NAME: "loss_utils.losses"
          _CLASS_NAME: "SigmoidForwardBinarize"
        "thresholds": [0.5]
    "weighted_hard_dice_BCE":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "WeightedLosses"
      "criterions":
        - _CLASS_INFO:
            _MODULE_NAME: "loss_utils.losses"
            _CLASS_NAME: "HardDice"
          "epsilon": 1.0E-8
          "binary_forward":
            _CLASS_INFO:
              _MODULE_NAME: "loss_utils.losses"
              _CLASS_NAME: "SigmoidForwardBinarize"
            "thresholds": [0.5]
        - _CLASS_INFO:
            _MODULE_NAME: "torch.nn"
            _CLASS_NAME: "BCEWithLogitsLoss"
      "weights": [0.8, 0.2]
  _CLASS_INFO:
    _MODULE_NAME: "loss_utils.criterions"
    _CLASS_NAME: "LossesMetrics"

_LOADER_TO_EVAL: _VAL_DATALOADER_CONFIG