_EXPERIMENT_DATA:
  batch_log_interval: 100
  best_metric_type: high
  num_epochs: 80
  saving_metric: dice_metric
_EXPERIMENT_DIR: ./example_experiment/train_example_all_no_noise_patient_seq_norm_b5_BN/
_LOOKAHEAD_OPTIM:
  params:
    alpha: 0.5
    k: 5
  use_lookahead: true
_LOSSES_METRICS_CONFIG:
  _CLASS_INFO:
    _CLASS_NAME: LossesMetrics
    _MODULE_NAME: loss_utils.criterions
  criterions_dict:
    dice_metric:
      _CLASS_INFO:
        _CLASS_NAME: DiceMetric
        _MODULE_NAME: loss_utils.losses
      binarize_func:
        _CLASS_INFO:
          _CLASS_NAME: SigmoidBinarize
          _MODULE_NAME: loss_utils.losses
        thresholds:
        - 0.5
      epsilon: 1.0e-08
    hard_dice:
      _CLASS_INFO:
        _CLASS_NAME: HardDice
        _MODULE_NAME: loss_utils.losses
      binary_forward:
        _CLASS_INFO:
          _CLASS_NAME: SigmoidForwardBinarize
          _MODULE_NAME: loss_utils.losses
        thresholds:
        - 0.5
      epsilon: 1.0e-08
    loss_baseline:
      _CLASS_INFO:
        _CLASS_NAME: BaselineLoss
        _MODULE_NAME: loss_utils.losses
      bce_weight: 0.0
      dice_smooth: 1.0e-08
    loss_bce:
      _CLASS_INFO:
        _CLASS_NAME: BCEWithLogitsLoss
        _MODULE_NAME: torch.nn
    loss_dice:
      _CLASS_INFO:
        _CLASS_NAME: SoftDice
        _MODULE_NAME: loss_utils.losses
      epsilon: 1.0e-08
      pred_process:
        _CLASS_INFO:
          _CLASS_NAME: Sigmoid
          _MODULE_NAME: torch.nn
    weighted_hard_dice_BCE:
      _CLASS_INFO:
        _CLASS_NAME: WeightedLosses
        _MODULE_NAME: loss_utils.losses
      criterions:
      - _CLASS_INFO:
          _CLASS_NAME: HardDice
          _MODULE_NAME: loss_utils.losses
        binary_forward:
          _CLASS_INFO:
            _CLASS_NAME: SigmoidForwardBinarize
            _MODULE_NAME: loss_utils.losses
          thresholds:
          - 0.5
        epsilon: 1.0e-08
      - _CLASS_INFO:
          _CLASS_NAME: BCEWithLogitsLoss
          _MODULE_NAME: torch.nn
      weights:
      - 0.8
      - 0.2
_LR_SCHEDULER:
  _CLASS_INFO:
    _CLASS_NAME: TorchLRScheduler
    _MODULE_NAME: train_utils
  name: ReduceLROnPlateau
  param_dict:
    cooldown: 0
    factor: 0.9
    patience: 3
    threshold: 0.001
    verbose: true
  step_type: use_val
_MODEL_CHECKPOINT: null
_MODEL_CONFIG:
  _CLASS_INFO:
    _CLASS_NAME: BaselineModelGetter
    _MODULE_NAME: new_models.models
  smp_name: Unet
  smp_params:
    activation: null
    classes: 1
    decoder_use_batchnorm: true
    encoder_name: efficientnet-b5
    encoder_weights: imagenet
_MODEL_PARAM_PREP: null
_NEW_CKP_FORMAT: true
_OPTIMIZATION_LOSS: loss_bce
_OPTIMIZER:
  _CLASS_INFO:
    _CLASS_NAME: OptimGetter
    _MODULE_NAME: train_utils
  module_name: catalyst.contrib.nn
  name: RAdam
  param_dict:
    lr: 0.001
    weight_decay: 0.001
_TRAIN_DATALOADER_CONFIG:
  _CLASS_INFO:
    _CLASS_NAME: BaselineDataloaderGetter
    _MODULE_NAME: new_datasets.dataloader
  batchsize: 8
  dataset:
    _CLASS_INFO:
      _CLASS_NAME: NewBaselineDatasetGetter
      _MODULE_NAME: new_datasets.datasets
    augmentation:
      _CLASS_INFO:
        _CLASS_NAME: Compose
        _MODULE_NAME: albumentations
      transforms:
      - _CLASS_INFO:
          _CLASS_NAME: Resize
          _MODULE_NAME: albumentations
        height: 512
        interpolation: 2
        width: 512
      - _CLASS_INFO:
          _CLASS_NAME: HorizontalFlip
          _MODULE_NAME: albumentations
        p: 0.5
      - _CLASS_INFO:
          _CLASS_NAME: ShiftScaleRotate
          _MODULE_NAME: albumentations
        border_mode: 0
        p: 1
        rotate_limit: 45
        scale_limit: 0.2
        shift_limit: 0.1
      - _CLASS_INFO:
          _CLASS_NAME: RandomCrop
          _MODULE_NAME: albumentations
        height: 384
        p: 1
        width: 384
      - _CLASS_INFO:
          _CLASS_NAME: IAAAdditiveGaussianNoise
          _MODULE_NAME: albumentations
        p: 0.2
      - _CLASS_INFO:
          _CLASS_NAME: IAAPerspective
          _MODULE_NAME: albumentations
        p: 0.5
      - _CLASS_INFO:
          _CLASS_NAME: OneOf
          _MODULE_NAME: albumentations
        p: 0.3
        transforms:
        - _CLASS_INFO:
            _CLASS_NAME: ElasticTransform
            _MODULE_NAME: albumentations
          alpha: 120
          alpha_affine: 3.6
          sigma: 6
        - _CLASS_INFO:
            _CLASS_NAME: GridDistortion
            _MODULE_NAME: albumentations
        - _CLASS_INFO:
            _CLASS_NAME: OpticalDistortion
            _MODULE_NAME: albumentations
          distort_limit: 1
          shift_limit: 0.3
      - _CLASS_INFO:
          _CLASS_NAME: OneOf
          _MODULE_NAME: albumentations
        p: 0.9
        transforms:
        - _CLASS_INFO:
            _CLASS_NAME: CLAHE
            _MODULE_NAME: albumentations
          p: 1
        - _CLASS_INFO:
            _CLASS_NAME: RandomBrightnessContrast
            _MODULE_NAME: albumentations
          p: 1
        - _CLASS_INFO:
            _CLASS_NAME: RandomGamma
            _MODULE_NAME: albumentations
          p: 1
      - _CLASS_INFO:
          _CLASS_NAME: OneOf
          _MODULE_NAME: albumentations
        p: 0.9
        transforms:
        - _CLASS_INFO:
            _CLASS_NAME: IAASharpen
            _MODULE_NAME: albumentations
          p: 1
        - _CLASS_INFO:
            _CLASS_NAME: Blur
            _MODULE_NAME: albumentations
          blur_limit: 3
          p: 1
        - _CLASS_INFO:
            _CLASS_NAME: MotionBlur
            _MODULE_NAME: albumentations
          blur_limit: 3
          p: 1
    filters: null
    label2mask:
      _CLASS_INFO:
        _CLASS_NAME: SingleChannelMaskNumpy
        _MODULE_NAME: new_datasets.transforms
    normalization:
      _CLASS_INFO:
        _CLASS_NAME: NormalizePatientSeq
        _MODULE_NAME: data.data_utils
    smp_preprocessing: null
    splitter:
      _CLASS_INFO:
        _CLASS_NAME: GenSplit
        _MODULE_NAME: new_datasets.splits
      seed: 1
      test: 0.15
      train: 0.7
      val: 0.15
    splitter_key: train
  shuffle: true
_VAL_DATALOADER_CONFIG:
  _CLASS_INFO:
    _CLASS_NAME: BaselineDataloaderGetter
    _MODULE_NAME: new_datasets.dataloader
  batchsize: 8
  dataset:
    _CLASS_INFO:
      _CLASS_NAME: NewBaselineDatasetGetter
      _MODULE_NAME: new_datasets.datasets
    augmentation:
      _CLASS_INFO:
        _CLASS_NAME: Compose
        _MODULE_NAME: albumentations
      transforms:
      - _CLASS_INFO:
          _CLASS_NAME: Resize
          _MODULE_NAME: albumentations
        height: 512
        interpolation: 2
        width: 512
      - _CLASS_INFO:
          _CLASS_NAME: CenterCrop
          _MODULE_NAME: albumentations
        height: 384
        width: 384
    filters: null
    label2mask:
      _CLASS_INFO:
        _CLASS_NAME: SingleChannelMaskNumpy
        _MODULE_NAME: new_datasets.transforms
    normalization:
      _CLASS_INFO:
        _CLASS_NAME: NormalizePatientSeq
        _MODULE_NAME: data.data_utils
    smp_preprocessing: null
    splitter:
      _CLASS_INFO:
        _CLASS_NAME: GenSplit
        _MODULE_NAME: new_datasets.splits
      seed: 1
      test: 0.15
      train: 0.7
      val: 0.15
    splitter_key: val
  shuffle: false
_VAL_PLOTTING:
  0: 2
  5: 1
  10: 6
  20: 3
  30: 2
