---
_MODEL_CONFIG:
  "smp_name": "Unet"
  "smp_params":
    encoder_name: "efficientnet-b6"
    encoder_weights: "imagenet"
    activation: null
    classes: 2
  _CLASS_INFO:
    _MODULE_NAME: "new_models.models"
    _CLASS_NAME: "BaselineModelGetter"

_LOSS_CRITERION_CONFIG:
  "dice_smooth": 1e-8,
  "bce_weight": 0.5
  _CLASS_INFO:
    _MODULE_NAME: "loss_utils.losses"
    _CLASS_NAME: BaselineLoss

_DATASET_CONFIG:
  "params":
    idxs: "_SPLITS_CONFIG"
    hyperparams: None
    transform_x: "_TRANFORM_X_CONFIG"
    transform_y: "_TRANFORM_Y_CONFIG"
    proprocessing_func: None

  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.datasets"
    _CLASS_NAME: "BaselineDatasetGetter"

_SPLITS_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.splits"
    _CLASS_NAME: "GenSplit"

_TRANFORM_X_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.transforms"
    _CLASS_NAME: "Transform_X"

_TRANFORM_Y_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.transforms"
    _CLASS_NAME: "Transform_Y"
  