---
_EXPERIMENT_DIR: "./experiments/new_baseline_4/"
_MODEL_CHECKPOINT: null
_NEW_CKP_FORMAT: false

_EXPERIMENT_DATA:
  "num_epochs": 30
  "batch_log_interval": 20
  "best_metric_type": "low"
  "saving_metric": "loss_baseline"

_MODEL_CONFIG:
  "smp_name": "Unet"
  "smp_params":
    encoder_name: "efficientnet-b0"
    encoder_weights: "imagenet"
    activation: null
    classes: 2
  _CLASS_INFO:
    _MODULE_NAME: "new_models.models"
    _CLASS_NAME: "BaselineModelGetter"

_DATALOADER_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.dataloader"
    _CLASS_NAME: "BaselineDataloaderGetter"
  "batchsize": 64
  "shuffle": True
  "datasets":
    _CLASS_INFO:
      _MODULE_NAME: "new_datasets.datasets"
      _CLASS_NAME: "BaselineDatasetGetter"
    "splitter":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.splits"
        _CLASS_NAME: "GenSplit"
      "train": 0.7
      "val": 0.15
      "test": 0.15
      "seed": 1
    "transform_x":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "Transform_X"
      "dim": 224
    "transform_y":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "Transform_Y"
      "dim": 224
      "mask2label":
        _CLASS_INFO:
          _MODULE_NAME: "new_datasets.transforms"
          _CLASS_NAME: "BaselineMaskEncode"
    "preprocess_func":
      "encoder_name": "efficientnet-b6"
      "encoder_weights": "imagenet"
      _CLASS_INFO:
        _MODULE_NAME: "new_models.preprocessing"
        _CLASS_NAME: "BaselinePreprocessGetter"

_LOSSES_METRICS_CONFIG:
  "criterions_dict":
    "loss_baseline":
      "dice_smooth": 1.0E-8
      "bce_weight": 0.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "BaselineLoss"
    "loss_dice":
      "dice_smooth": 1.0E-8
      "bce_weight": 0.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "BaselineLoss"
    "loss_bce":
      "dice_smooth": 1.0E-8
      "bce_weight": 1.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "BaselineLoss"
  _CLASS_INFO:
    _MODULE_NAME: "loss_utils.criterions"
    _CLASS_NAME: "LossesMetrics"

_OPTIMIZATION_LOSS: "loss_baseline"

_LR_SCHEDULER:
  _CLASS_INFO:
    _MODULE_NAME: "train_utils"
    _CLASS_NAME: "TorchLRScheduler"
  "name": "ReduceLROnPlateau"
  "param_dict":
    "factor": 0.9
    "patience": 1
    "verbose": true
    "threshold": 0.001
    "cooldown": 0
  "step_type": "use_val"

_OPTIMIZER:
  _CLASS_INFO:
    _MODULE_NAME: "train_utils"
    _CLASS_NAME: "OptimGetter"
  "module_name": "catalyst.contrib.nn"
  "name": "RAdam"
  "param_dict": {"lr": 0.001}

_LOOKAHEAD_OPTIM:
  "use_lookahead": false
  "params": {k: 5, alpha: 0.5}
