---
_EXPERIMENT_DIR: "./experiments/albumentations_new_dice_example_15/"
_MODEL_CHECKPOINT: null
_NEW_CKP_FORMAT: false

_EXPERIMENT_DATA:
  "num_epochs": 40
  "batch_log_interval": 20
  "best_metric_type": "high"
  "saving_metric": "dice_metric"

_MODEL_CONFIG:
  "smp_name": "Unet"
  "smp_params":
    encoder_name: "efficientnet-b0"
    encoder_weights: "imagenet"
    activation: null
    classes: 1
  _CLASS_INFO:
    _MODULE_NAME: "new_models.models"
    _CLASS_NAME: "BaselineModelGetter"

_TRAIN_DATALOADER_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.dataloader"
    _CLASS_NAME: "BaselineDataloaderGetter"
  "batchsize": 64
  "shuffle": True
  "dataset":
    _CLASS_INFO:
      _MODULE_NAME: "new_datasets.datasets"
      _CLASS_NAME: "NewBaselineDatasetGetter"
    "splitter":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.splits"
        _CLASS_NAME: "GenSplit"
      "train": 0.7
      "val": 0.15
      "test": 0.15
      "seed": 1
    "label2mask":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "SingleChannelMaskNumpy"
    "augmentation":
      _CLASS_INFO:
        _MODULE_NAME: "albumentations"
        _CLASS_NAME: "Compose"
      transforms:
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "Resize"
          "height": 256
          "width": 256
          "interpolation": 2 # cubic
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "CenterCrop"
          "height": 192
          "width": 192
    "smp_preprocessing":
      "encoder_name": "efficientnet-b0"
      "pretrained": "imagenet"
      _CLASS_INFO:
        _MODULE_NAME: "segmentation_models_pytorch.encoders"
        _CLASS_NAME: "get_preprocessing_fn"
    "splitter_key": "train"
    "filters": null

_VAL_DATALOADER_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.dataloader"
    _CLASS_NAME: "BaselineDataloaderGetter"
  "batchsize": 64
  "shuffle": False
  "dataset":
    _CLASS_INFO:
      _MODULE_NAME: "new_datasets.datasets"
      _CLASS_NAME: "NewBaselineDatasetGetter"
    "splitter":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.splits"
        _CLASS_NAME: "GenSplit"
      "train": 0.7
      "val": 0.15
      "test": 0.15
      "seed": 1
    "label2mask":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "SingleChannelMaskNumpy"
    "augmentation":
      _CLASS_INFO:
        _MODULE_NAME: "albumentations"
        _CLASS_NAME: "Compose"
      transforms:
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "Resize"
          "height": 256
          "width": 256
          "interpolation": 2 # cubic
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "CenterCrop"
          "height": 192
          "width": 192
    "smp_preprocessing":
      "encoder_name": "efficientnet-b0"
      "pretrained": "imagenet"
      _CLASS_INFO:
        _MODULE_NAME: "segmentation_models_pytorch.encoders"
        _CLASS_NAME: "get_preprocessing_fn"
    "splitter_key": "val"
    "filters": null

_LOSSES_METRICS_CONFIG:
  "criterions_dict":
    "loss_baseline":
      "dice_smooth": 1.0E-8
      "bce_weight": 0.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "BaselineLoss"
    "combined_dice_bce":
      "epsilon": 1.0E-8
      "bce_weight": 0.5
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "CombinedDiceBCE"
    "loss_dice":
      "epsilon": 1.0E-8
      "bce_weight": 0.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "CombinedDiceBCE"
    "loss_bce":
      "epsilon": 1.0E-8
      "bce_weight": 1.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "CombinedDiceBCE"
    "dice_metric":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "DiceMetric"
      "epsilon": 1.0E-8
      "binarize_func":
        _CLASS_INFO:
          _MODULE_NAME: "loss_utils.losses"
          _CLASS_NAME: "SigmoidBinarize"
        "thresholds": [0.5]
    "hard_dice":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "HardDice"
      "epsilon": 1.0E-8
      "binary_forward":
        _CLASS_INFO:
          _MODULE_NAME: "loss_utils.losses"
          _CLASS_NAME: "SigmoidForwardBinarize"
        "thresholds": [0.5]
    "weighted_hard_dice_BCE":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "WeightedLosses"
      "criterions":
        - _CLASS_INFO:
            _MODULE_NAME: "loss_utils.losses"
            _CLASS_NAME: "HardDice"
          "epsilon": 1.0E-8
          "binary_forward":
            _CLASS_INFO:
              _MODULE_NAME: "loss_utils.losses"
              _CLASS_NAME: "SigmoidForwardBinarize"
            "thresholds": [0.5]
        - _CLASS_INFO:
            _MODULE_NAME: "torch.nn"
            _CLASS_NAME: "BCEWithLogitsLoss"
      "weights": [0.8, 0.2]
  _CLASS_INFO:
    _MODULE_NAME: "loss_utils.criterions"
    _CLASS_NAME: "LossesMetrics"

_OPTIMIZATION_LOSS: "weighted_hard_dice_BCE"

_LR_SCHEDULER:
  _CLASS_INFO:
    _MODULE_NAME: "train_utils"
    _CLASS_NAME: "TorchLRScheduler"
  "name": "ReduceLROnPlateau"
  "param_dict":
    "factor": 0.9
    "patience": 2
    "verbose": true
    "threshold": 0.001
    "cooldown": 0
  "step_type": "use_val"

_OPTIMIZER:
  _CLASS_INFO:
    _MODULE_NAME: "train_utils"
    _CLASS_NAME: "OptimGetter"
  "module_name": "catalyst.contrib.nn"
  "name": "RAdam"
  "param_dict": {"lr": 0.001}

_LOOKAHEAD_OPTIM:
  "use_lookahead": false
  "params": {k: 5, alpha: 0.5}
