---
_EXPERIMENT_DIR: "./experiments/train_example/"
_MODEL_CHECKPOINT: null
_NEW_CKP_FORMAT: false

_EXPERIMENT_DATA:
  "num_epochs": 50
  "batch_log_interval": 100
  "best_metric_type": "high"
  "saving_metric": "dice_metric"

_MODEL_CONFIG:
  "smp_name": "Unet"
  "smp_params":
    encoder_name: "efficientnet-b4"
    encoder_weights: "imagenet"
    decoder_use_batchnorm: False
    activation: null
    classes: 1
  _CLASS_INFO:
    _MODULE_NAME: "new_models.models"
    _CLASS_NAME: "BaselineModelGetter"

_TRAIN_DATALOADER_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.dataloader"
    _CLASS_NAME: "BaselineDataloaderGetter"
  "batchsize": 8
  "shuffle": True
  "dataset":
    _CLASS_INFO:
      _MODULE_NAME: "new_datasets.datasets"
      _CLASS_NAME: "NewBaselineDatasetGetter"
    "splitter":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.splits"
        _CLASS_NAME: "GenSplit"
      "train": 0.7
      "val": 0.15
      "test": 0.15
      "seed": 1
    "label2mask":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "SingleChannelMaskNumpy"
    "augmentation":
      _CLASS_INFO:
        _MODULE_NAME: "albumentations"
        _CLASS_NAME: "Compose"
      transforms:
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "Resize"
          "height": 512
          "width": 512
          "interpolation": 2 # cubic
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "HorizontalFlip"
          "p": 0.5
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "ShiftScaleRotate"
          "scale_limit": 0.2
          "rotate_limit": 45
          "shift_limit": 0.1
          "p": 1
          "border_mode": 0
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "RandomCrop"
          "height": 384
          "width": 384
          "p": 1
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "IAAAdditiveGaussianNoise"
          "p": 0.2
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "IAAPerspective"
          "p": 0.5
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "OneOf"
          "transforms":
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "ElasticTransform"
              "alpha": 120
              "sigma": 6
              "alpha_affine": 3.6
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "GridDistortion"
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "OpticalDistortion"
              "distort_limit": 1
              "shift_limit": 0.3
          "p": 0.3
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "OneOf"
          "transforms":
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "CLAHE"
              "p": 1
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "RandomBrightnessContrast"
              "p": 1
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "RandomGamma"
              "p": 1
          "p": 0.9
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "OneOf"
          "transforms":
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "IAASharpen"
              "p": 1
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "Blur"
              "p": 1
              "blur_limit": 3
            - _CLASS_INFO:
                _MODULE_NAME: "albumentations"
                _CLASS_NAME: "MotionBlur"
              "p": 1
              "blur_limit": 3
          "p": 0.9

    "smp_preprocessing":
      "encoder_name": "efficientnet-b4"
      "pretrained": "imagenet"
      _CLASS_INFO:
        _MODULE_NAME: "segmentation_models_pytorch.encoders"
        _CLASS_NAME: "get_preprocessing_fn"
    "splitter_key": "train"
    "filters": null

_VAL_DATALOADER_CONFIG:
  _CLASS_INFO:
    _MODULE_NAME: "new_datasets.dataloader"
    _CLASS_NAME: "BaselineDataloaderGetter"
  "batchsize": 8
  "shuffle": False
  "dataset":
    _CLASS_INFO:
      _MODULE_NAME: "new_datasets.datasets"
      _CLASS_NAME: "NewBaselineDatasetGetter"
    "splitter":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.splits"
        _CLASS_NAME: "GenSplit"
      "train": 0.7
      "val": 0.15
      "test": 0.15
      "seed": 1
    "label2mask":
      _CLASS_INFO:
        _MODULE_NAME: "new_datasets.transforms"
        _CLASS_NAME: "SingleChannelMaskNumpy"
    "augmentation":
      _CLASS_INFO:
        _MODULE_NAME: "albumentations"
        _CLASS_NAME: "Compose"
      transforms:
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "Resize"
          "height": 512
          "width": 512
          "interpolation": 2 # cubic
        - _CLASS_INFO:
            _MODULE_NAME: "albumentations"
            _CLASS_NAME: "CenterCrop"
          "height": 384
          "width": 384
    "smp_preprocessing":
      "encoder_name": "efficientnet-b4"
      "pretrained": "imagenet"
      _CLASS_INFO:
        _MODULE_NAME: "segmentation_models_pytorch.encoders"
        _CLASS_NAME: "get_preprocessing_fn"
    "splitter_key": "val"
    "filters": null

_LOSSES_METRICS_CONFIG:
  "criterions_dict":
    "loss_baseline":
      "dice_smooth": 1.0E-8
      "bce_weight": 0.0
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "BaselineLoss"
    "loss_dice":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "SoftDice"
      "epsilon": 1.0E-8
      "pred_process":
        _CLASS_INFO:
          _MODULE_NAME: "torch.nn"
          _CLASS_NAME: "Sigmoid"
    "loss_bce":
      _CLASS_INFO:
        _MODULE_NAME: "torch.nn"
        _CLASS_NAME: "BCEWithLogitsLoss"
    "dice_metric":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "DiceMetric"
      "epsilon": 1.0E-8
      "binarize_func":
        _CLASS_INFO:
          _MODULE_NAME: "loss_utils.losses"
          _CLASS_NAME: "SigmoidBinarize"
        "thresholds": [0.5]
    "hard_dice":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "HardDice"
      "epsilon": 1.0E-8
      "binary_forward":
        _CLASS_INFO:
          _MODULE_NAME: "loss_utils.losses"
          _CLASS_NAME: "SigmoidForwardBinarize"
        "thresholds": [0.5]
    "weighted_hard_dice_BCE":
      _CLASS_INFO:
        _MODULE_NAME: "loss_utils.losses"
        _CLASS_NAME: "WeightedLosses"
      "criterions":
        - _CLASS_INFO:
            _MODULE_NAME: "loss_utils.losses"
            _CLASS_NAME: "HardDice"
          "epsilon": 1.0E-8
          "binary_forward":
            _CLASS_INFO:
              _MODULE_NAME: "loss_utils.losses"
              _CLASS_NAME: "SigmoidForwardBinarize"
            "thresholds": [0.5]
        - _CLASS_INFO:
            _MODULE_NAME: "torch.nn"
            _CLASS_NAME: "BCEWithLogitsLoss"
      "weights": [0.8, 0.2]
  _CLASS_INFO:
    _MODULE_NAME: "loss_utils.criterions"
    _CLASS_NAME: "LossesMetrics"

_OPTIMIZATION_LOSS: "loss_bce"

_LR_SCHEDULER:
  _CLASS_INFO:
    _MODULE_NAME: "train_utils"
    _CLASS_NAME: "TorchLRScheduler"
  "name": "ReduceLROnPlateau"
  "param_dict":
    "factor": 0.9
    "patience": 3
    "verbose": true
    "threshold": 0.001
    "cooldown": 0
  "step_type": "use_val"

_OPTIMIZER:
  _CLASS_INFO:
    _MODULE_NAME: "train_utils"
    _CLASS_NAME: "OptimGetter"
  "module_name": "catalyst.contrib.nn"
  "name": "RAdam"
  "param_dict": {"lr": 0.001, "weight_decay": 0.001}

_MODEL_PARAM_PREP:
  _CLASS_INFO:
    _MODULE_NAME: "new_models.models"
    _CLASS_NAME: "CatalystModelParamPrep"
  "layerwise_params":
    "encoder*": {"lr": 0.0001, "weight_decay": 0.0001}

_LOOKAHEAD_OPTIM:
  "use_lookahead": true
  "params": {k: 5, alpha: 0.5}

# a dict of batch_idx: image_idx_in_batch to plot
_VAL_PLOTTING: {0: 2, 10: 6, 20: 3}
